<?php

namespace Pi2\Fractalia\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColumnaeventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColumnaeventoRepository extends EntityRepository
{
    /**
     * Se obtienen todos los id de mensaje de todas los resumenes que estan presentes las incidencias
     * 
     * @param array $incidencias
     * @return mixed Result|Exception
     */
    public function getIdByIncidencias($incidencias)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT DISTINCT(e.id) AS id FROM FractaliaSmsBundle:Columnaevento e
                 WHERE e.incidencia IN (:incidencias)
                 "
            )->setParameters(array('incidencias' => $incidencias));

        try
        {
            $resultado = $query->getResult();
            if (count($resultado) == 0)
            {
                return 0;
            }
            if (count($resultado) > 0)
            {
                return $resultado;
            }
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
        catch (\Doctrine\Orm\ORMException $e)
        {
            return $e;
        }
    }
}