<?php

namespace Pi2\Fractalia\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ColumnaresumenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColumnaresumenRepository extends EntityRepository
{

    /**
     * Se obtienen todos los id de mensaje de todas los resumenes que estan presentes las incidencias
     * 
     * @param array $incidencias
     * @return mixed Result|Exception
     */
    public function getMensajesByIncidencias($incidencias)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT DISTINCT(r.mensaje) AS mensaje_id FROM FractaliaSmsBundle:Columnaresumen r
                 WHERE r.incidencia IN (:incidencias)
                 "
            )->setParameters(array('incidencias' => $incidencias));

        try
        {
            $resultado = $query->getResult();
            if (count($resultado) == 0)
            {
                return 0;
            }
            if (count($resultado) > 0)
            {
                return $resultado;
            }
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
        catch (\Doctrine\Orm\ORMException $e)
        {
            return $e;
        }
    }
    
    /**
     * Se obtienen todos los id de mensaje de todas los resumenes que estan presentes las incidencias
     * 
     * @param array $incidencias
     * @return mixed Result|Exception
     */
    public function getResumenesByIncidencias($incidencias)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT r FROM FractaliaSmsBundle:Columnaresumen r
                 WHERE r.incidencia IN (:incidencias)
                 "
            )->setParameters(array('incidencias' => $incidencias));

        try
        {
            $resultado = $query->getResult();
            if (count($resultado) == 0)
            {
                return 0;
            }
            if (count($resultado) > 0)
            {
                return $resultado;
            }
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
        catch (\Doctrine\Orm\ORMException $e)
        {
            return $e;
        }
    }
    
    /**
     * Se obtienen todos los resumenes de los mensajes a borrar
     * 
     * @param array $arrayMensajesId
     * @return mixed Result|Exception
     */
    public function getResumenesByMensajesId($arrayMensajesId)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT r FROM FractaliaSmsBundle:Columnaresumen r
                 WHERE r.mensaje IN (:mensajes)
                 "
            )->setParameters(array('mensajes' => $arrayMensajesId));

        try
        {
            $resultado = $query->getResult();
            if (count($resultado) == 0)
            {
                return 0;
            }
            if (count($resultado) > 0)
            {
                return $resultado;
            }
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
        catch (\Doctrine\Orm\ORMException $e)
        {
            return $e;
        }
    }
    

}
