<?php

namespace Pi2\Fractalia\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NombrecortoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeRepository extends EntityRepository
{
    /**
     * Se obtienen todos los id de mensaje de todas los resumenes que estan presentes las incidencias
     * 
     * @param array $eventos
     * @return mixed Result|Exception
     */
    public function getIdByEventos($eventos)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT DISTINCT(m.id) AS id FROM FractaliaSmsBundle:Mensaje m
                 WHERE m.columnaEvento IN (:eventos)
                 "
            )->setParameters(array('eventos' => $eventos));

        try
        {
            $resultado = $query->getResult();
            if (count($resultado) == 0)
            {
                return 0;
            }
            if (count($resultado) > 0)
            {
                return $resultado;
            }
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
        catch (\Doctrine\Orm\ORMException $e)
        {
            return $e;
        }
    }
}
