<?php

namespace Pi2\Fractalia\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NombretsolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NombretsolRepository extends EntityRepository
{
    
    /*
     * Retorna un array con los datos del Nombre TSOL
     * 
     */

    public function getTsol()
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT t FROM Pi2\Fractalia\SmsBundle\Entity\Nombretsol t"
            );
        try
        {
            return $query->getOneOrNullResult();
            
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
    }
}
