<?php

namespace Pi2\Fractalia\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NombrecortoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsRepository extends EntityRepository
{
    /*
     * 
     * Se obitienen los sms buscados en caso de encontrarlos
     * @param string $string cadena a buscar
     * @return mixed collection or null
     */
    //
    public function getByString($string)
    {
        $query = $this->getEntityManager()->createQuery(
                "SELECT s.* FROM Pi2\Fractalia\SmsBundle\Entity\Sms s
                 WHERE s.destinatario = :string")
            ->setParameters(array('string' => $string));

        try
        {
            return $query->getResult();
        }
        catch (\Doctrine\Orm\NoResultException $e)
        {
            return null;
        }
        catch (\Doctrine\Orm\ORMException $e)
        {
            print_r($e->getMessage());
            return $e;
        }
    }
}
