<?php

namespace Pi2\Fractalia\SmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NombrecortoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsRepository extends EntityRepository {
    /*
     * 
     * Se obitienen los sms buscados en caso de encontrarlos
     * @param string $string cadena a buscar
     * @return mixed collection or null
     */

    //
    public function findByString($string) {
        $query = $this->getEntityManager()->createQuery(
                        "SELECT s 
                    FROM FractaliaSmsBundle:Sms s
                        INNER JOIN FractaliaSmsBundle:Mensaje m
                            WITH m.id = s.mensaje
                    WHERE
                        s.estadoEnvio in ('ERROR', 'POR_ENVIAR', 'ERROR_BUILD', 'ENVIADO')
                    AND
                    (                        
                        s.destinatario = :string OR
                        s.estadoEnvio = :string OR
                        s.respuestaApi = :string OR
                        s.fechaCreacion = :string OR
                        m.nombrePlantilla = :string OR
                        m.texto LIKE :pattern
                    )
                    ORDER BY 
                        s.fechaCreacion DESC"
                )->setParameters(
                array(
                    'string' => $string,
                    'pattern' => "%" . $string . "%"
                )
        );

        try {
            return $query->getResult();
        } catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        } catch (\Doctrine\Orm\ORMException $e) {
            print_r($e->getMessage());
            return $e;
        }
    }

}
