<?php

namespace Pi2\Fractalia\Entity\SGSD;

use Doctrine\ORM\EntityRepository;

/**
 * AccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccionRepository extends EntityRepository
{

    public function removeAccionByIncidenciaId($id)
    {
        $deleteQuery = $this->getEntityManager()->createQuery(
                'DELETE FROM Pi2\Fractalia\Entity\SGSD\Accion a 
                WHERE a.incidencia = :id')
            ->setParameters(array('id' => $id));
        return $deleteQuery->execute();
    }

}
