<?php

namespace Pi2\Fractalia\Entity\SGSD;

use Doctrine\ORM\EntityRepository;

/**
 * IncidenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DescripcionRepository extends EntityRepository
{

    public function removeDescripcionByIncidenciaId($id)
    {
        $deleteQuery = $this->getEntityManager()->createQuery(
                'DELETE FROM Pi2\Fractalia\Entity\SGSD\Descripcion d 
                WHERE d.incidencia = :id')
            ->setParameters(array('id' => $id));
        return $deleteQuery->execute();
    }

}
