imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: notice
            buffer_size: 30
            handler:      nested
            channels: ["!listener", "!maintain"]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        listener:
            type:   stream
            path:   "%kernel.logs_dir%/listener.log"
            level:  info
            channels: [listener]
        maintain:
            type:   stream
            path:   "%kernel.logs_dir%/maintain.log"
            level:  info
            channels: [maintain]
