SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM Incidencia;
ALTER TABLE Incidencia AUTO_INCREMENT = 1;

DELETE FROM Descripcion;
ALTER TABLE Descripcion AUTO_INCREMENT = 1;

DELETE FROM Accion;
ALTER TABLE Accion AUTO_INCREMENT = 1;

DELETE FROM InfoAdjunto;
ALTER TABLE InfoAdjunto AUTO_INCREMENT = 1;

DELETE FROM Nombretsol;
ALTER TABLE Nombretsol AUTO_INCREMENT = 1;

DELETE FROM Resolucion;
ALTER TABLE Resolucion AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
